blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    path('ticket', views.ticket, name="ticket"),
    path("search/" , views.search_post , name="search_post"),
    path("profile/",views.profile , name="profile"),
    path("profile/create_posts",views.create_posts , name="create_posts"),
    path("profile/delete_posts/<post_id>", views.delete_posts, name="delete_posts"),
    path("profile/delete_image/<image_id>", views.delete_image, name="delete_image"),
    path("profile/create_posts/<post_id>", views.edit_posts, name="edit_posts"),
    # path("login",views.user_login,name="login")
    path("login/",auth_views.LoginView.as_view(),name="login"),
    # path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("logout/",views.log_out,name="logout"),
    path("password_change/",auth_views.PasswordChangeView.as_view(success_url="done") , name="password_change"),
    path("password_change/done/",auth_views.PasswordChangeDoneView.as_view(),name="password_change_done"),
    path("password-reset/",auth_views.PasswordResetView.as_view(success_url="done"),name="password_reset"),
    path("password-reset/done/",auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
    path("password-reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(success_url="/blog/password-reset/complete"),name="password_reset_confirm"),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("register/",views.register,name="register"),
    path("account/edit",views.edit_account , name="edit_account"),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment,Post,User,Account
from django.contrib.auth.forms import AuthenticationForm

class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!")
            else:
                return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("نام کوتاه است")
            else:
                return name

    class Meta:
        model = Comment
        fields = ['name', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول ")
    image2 = forms.ImageField(label="تصویر دوم")

    class Meta:
        model = Post
        fields = ['title', 'description', "reading_time","category"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, required=True , label="username or phone")
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)

class UserRegisterForm(forms.ModelForm):
    password=forms.CharField(max_length=20 , widget=forms.PasswordInput , label="password")
    password2 = forms.CharField(max_length=20 , widget=forms.PasswordInput , label="repeat password")
    class Meta:
        model=User
        fields=["username","first_name","last_name","email"]
    def clean_password2(self):
        cd=self.cleaned_data
        if cd["password"] != cd["password2"] :
            raise forms.ValidationError("error not same")
        return cd["password2"]

class EditUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=["first_name","last_name"]


class  EditAccountForm(forms.ModelForm):
        class Meta:
            model=Account
            fields=["user","date_of_birth","bio","job","photo"]

blog/views.py
import postgres
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery, TrigramSimilarity
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


def index(request):
    return render(request, "blog/index.html")


def post_list(request,category=None):
    if category is not None:
        posts=Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    print(posts, type(posts))
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    print(posts, type(posts))
    context = {
        'posts': posts,
    }
    return render(request, "blog/list.html", context)

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name = "blog/list.html"


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, "blog/detail.html", context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "blog/detail.html"


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(message=cd['message'], name=cd['name'], email=cd['email'],
                                  phone=cd['phone'], subject=cd['subject'])
            return redirect("blog:index")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, "forms/comment.html", context)


def search_post(request):
    query = None
    results = []
    print(request.GET)
    print(request.GET.get("query"))
    if "query" in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)) \
                .filter(similarity__gt=0.1)
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)) \
                .filter(similarity__gt=0.1)
            results = (results1|results2).order_by('-similarity')
            print(results1)
            print(results2)
            print(results)
    context = {
        "query": query,
        "results": results
    }
    return render(request, "blog/search.html", context)


@login_required
def profile(request):
    user = request.user
    posts = Post.published.filter(author=user)
    # print(posts)
    # print(user)
    # print(user.username)
    return render(request, "./blog/profile.html", {"posts": posts})

@login_required
def create_posts(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            # img1=Image.objects.create(image_file=form.cleaned_data['image1'],post=post)
            # post.images.add(img1)
            # img2=Image.objects.create(image_file=form.cleaned_data['image2'],post=post)
            # post.images.add(img2)
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect("blog:profile")
    else:
        form = CreatePostForm()
    return render(request, "forms/create_posts.html", {"form": form})

@login_required
def delete_posts(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect("blog:profile")
    return render(request, "forms/delete_posts.html", {"posts": post})

@login_required
def edit_posts(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':

        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect("blog:profile")
    else:
        form = CreatePostForm(instance=post)
    return render(request, "forms/create_posts.html", {"form": form, "post": post})

@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect("blog:profile")
    # return render(request, "forms/delete_posts.html", {"image": image})

# def user_login(request):
#     if request.method=="POST" :
#         form=LoginForm(request.POST)
#         if form.is_valid():
#             cd=form.cleaned_data
#             user=authenticate(request,username=cd["username"],password=cd["password"])
#             if user is not None:
#                 if user.is_active:
#                     login(request,user)
#                     return redirect("blog:profile")
#                 else:
#                     return HttpResponse("u are  deactive")
#             else:
#                 return HttpResponse("u re none")
#     else:
#         form=LoginForm()
#     return render(request,"forms/login.html",{"form":form})
def log_out(request):
    logout()
    return redirect(request.META.get("HTTP_REFERER"))
    # return redirect("blog:index")

def register(request):
    if request.method=="POST":
        form=UserRegisterForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data["password"])
            user.save()
            Account.objects.create(user=user)
            return render(request, "registration/register_done.html", {"user":user})
    else:
        form=UserRegisterForm()
    return render(request,"registration/register.html",{"form":form})


@login_required
def edit_account(request):
    if request.method=="POST":
        user_form=EditUserForm(request.POST,instance=request.user)
        account_form=EditAccountForm(request.POST , instance=request.user.account , files=request.FILES)
        if user_form.is_valid() and account_form.is_valid():
            account_form.save()
            user_form.save()
    else:
        user_form=EditUserForm(instance=request.user)
        account_form=EditAccountForm(instance=request.user.account)
    context={
        "user_form":user_form ,
        "account_form":account_form
    }
    return render(request,"registration/edit_account.html",context)

blog/templates/blog/detail.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load static %}
{% block title %}post detail{% endblock %}

{% block content %}
    <h1 class="post-detail" >{{ post.title}}</h1>
    <p class="author">author: {{ post.author }}</p>
    <h1>عکس نویسنده</h1>
    <img src="{{  post.author.account.photo.url }}" >
    <span class="pub-date">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</span>
    <div>
        {% for img in post.images.all %}
{#            images => related name ast#}
            <img src="{{ img.image_file.url }}" alt="{{ img.title }}">
        {% endfor %}
    </div>
    <div class="des">

    <p class="des-p">{{ post.description | linebreaks }}</p>
    </div>
    <hr>

    <div>
    {% with comments.count as cm_count%}
    {{ cm_count }} comment{{ cm_count|pluralize }}
    </div>

     <div>
     {% for cm in comments %}
         <img src="{% static  'avatar/avatar.png' %}">
         {{ cm.body|linebreaks}}
         <br>
         {{ cm.name }}
     {% empty %}
         کامنتی وجود ندارد!
     {% endfor %}
     </div>
    {% endwith %}
    <form method="post" action="{% url 'blog:post_comment' post.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="افزودن کامنت">
    </form>
{% endblock %} 

blog/templates/blog/index.html
{% extends 'parent/base.html' %}
{% load blog_tags %}
{% block title %}post list{% endblock %}
{% block content %}
    <h2> آمار </h2>
    <p> تعداد پست: {% total_posts %} </p>
    <p> تعداد کامنت: {% total_comments %}</p>
    <p> تاریخ آخرین پست:{% last_post_date %}</p>

    {% latest_posts 5 %}

    <h2>محبوب ترین پست ها</h2>
    {%  most_popular_posts 3 as pop_posts %}
    {% for post in pop_posts %}
        <br>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}: with {{ post.comments_count }} comments</a>
    {% endfor %}

{% endblock %}

blog/templates/blog/list.html
<!--برای پسن لیست در ویو برگردانده میشه-->
{% extends 'parent/base.html' %}
{% block title %}post list{% endblock %}
{% block content %}

<h1 class="post-list">post list</h1>
{% if category %}
    <a href="{% url 'blog:post_list'  %}">list posts of {{ category }}</a>
{% else %}
        <a href="{% url 'blog:post_list'  %}">list posts </a>
{% endif %}
<a href="{% url 'blog:post_list_category' "تکنولوژی" %}">
تکنولوژی
</a>
<ol role="list">
<!--     styl e="--length: {{ posts|length }}" -->
    {% for post in posts %}
        <li>
<!--             style="--i: {{ forloop.counter }}"-->
        <h3 class="post-title">
        <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
        </h3>
        <p class="descr"> {{ post.description | truncatewords:4 }}</p>
        <img src="{{ post.images.first.image_file.url }}" alt="{{post.images.first.title}}">
<!--   images =>relatedname dar foreinkey         -->
<!--            first=> avvali ro neshoon bede  -->
<!--            url =>یعنی یو ار ال تصویر رو برداره-->
        </li>
    {% endfor %}
</ol>

{#    {% include "partials/pagination.html" with page=page_obj%}#}
    {% include "partials/pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/profile.html
<!--برای پسن لیست در ویو برگردانده میشه-->
{% extends 'parent/base.html' %}
{% block title %}profile{% endblock %}
{% block content %}
    <p>
    <a href="{% url 'blog:create_posts' %}">
        ایجاد پست جدید
    </a>
    </p>
    <table style="width: 80% ; border: 2px solid black ; text-align: right ;direction: rtl">
<tr>
    <th>
        ردیف
    </th>

    <th>
        مشاهده
    </th>
    <th>
        ویرایش
    </th>
    <th>
        حذف
    </th>
</tr>
        {% for post in posts %}
            <tr>
                    <td>
                    {{ forloop.counter }}
                    </td>
                    <td>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
                        </td>
                        <td>
                <a href="{% url "blog:edit_posts" post.id %}">
                    ویرایش
                </a>
                        </td>
                        <td>
                        <a href="{% url 'blog:delete_posts' post.id%}">
                            حذف
                        </a>
                        </td>
               </tr>
         {% endfor %}
    </table>
    <a href="{% url 'blog:password_change'%}">
    change password
    </a>
    <a href="{% url "blog:logout" %}">
logout
    </a>
{% endblock  %}

blog/templates/blog/search.html
{% extends 'parent/base.html' %}
{% block title %}post search{% endblock %}
{% block content %}
    {% if query %}
         {{ results.count }}: نتایج جستجو برای {{ query }}
    {% endif %}
    <br>
    {% for post in results %}
        <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
        <p>{{ post.description }}</p>
    {% empty %}
        هیچ نتیجه ای یافت نشد
    {% endfor %}

{% endblock %}